import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:intl/intl.dart';

import 'core/providers/firebase_providers.dart';
import 'features/auth/admin_login_page.dart';
import 'features/content/content_page.dart';
import 'features/dashboard/dashboard_page.dart';
import 'features/parent_linking/link_requests_page.dart';
import 'features/payments/payments_page.dart';
import 'features/sessions/sessions_page.dart';
import 'features/tutor_applications/tutor_applications_page.dart';
import 'features/users/users_page.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Suklu Admin Panel (Flutter Web)
//
// Restricted to super_admin / academic_staff — verified via Firebase custom claims.
// Deploy: flutter build web && firebase deploy --only hosting
// ─────────────────────────────────────────────────────────────────────────────
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeDateFormatting('fr');
  Intl.defaultLocale = 'fr';
  // TODO: replace with real firebase_options generated by flutterfire configure
  await Firebase.initializeApp(
    options: const FirebaseOptions(
      apiKey:            'AIzaSyA3PWu3omWkAliC4AlQXBSHo2LBsNDpOwM',
      appId:             '1:765014148505:web:b8e8453355c7b4297b3f08',
      messagingSenderId: '765014148505',
      projectId:         'suklu-prod',
      storageBucket:     'suklu-prod.firebasestorage.app',
      authDomain:        'suklu-prod.firebaseapp.com',
      measurementId:     'G-RCX1P41D2R',
    ),
  );
  
  // Connect to local Firebase emulators for development
  try {
    await FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
    await FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  } catch (e) {
    // Emulator already initialized or not running
  }
  
  runApp(const ProviderScope(child: SukluAdminApp()));
}

// ── Router ────────────────────────────────────────────────────────────────────
final _routerProvider = Provider<GoRouter>((ref) {
  final authState = ref.watch(authStateProvider);

  // Create a notifier for router refresh on auth changes
  final notifier = ValueNotifier<bool>(false);
  ref.listen(authStateProvider, (prev, next) {
    notifier.value = !notifier.value; // Toggle to trigger refresh
  });

  return GoRouter(
    initialLocation: '/dashboard',
      refreshListenable: notifier,
    redirect: (context, state) {
      final isLoggedIn = authState.valueOrNull != null;
      final isLoginRoute = state.matchedLocation == '/login';

      if (!isLoggedIn && !isLoginRoute) return '/login';
      if (isLoggedIn  &&  isLoginRoute) return '/dashboard';
      return null;
    },
    routes: [
      GoRoute(path: '/login',        builder: (_, __) => const AdminLoginPage()),
      GoRoute(path: '/dashboard',    builder: (_, __) => const _AdminShell(child: DashboardPage())),
      GoRoute(path: '/users',        builder: (_, __) => const _AdminShell(child: UsersPage())),
      GoRoute(path: '/applications', builder: (_, __) => const _AdminShell(child: TutorApplicationsPage())),
      GoRoute(path: '/link-requests',builder: (_, __) => const _AdminShell(child: LinkRequestsPage())),
      GoRoute(path: '/sessions',     builder: (_, __) => const _AdminShell(child: SessionsPage())),
      GoRoute(path: '/payments',     builder: (_, __) => const _AdminShell(child: PaymentsPage())),
      GoRoute(path: '/content',      builder: (_, __) => const _AdminShell(child: ContentPage())),
    ],
  );
});

class SukluAdminApp extends ConsumerWidget {
  const SukluAdminApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(_routerProvider);
    return MaterialApp.router(
      title: 'Suklu Admin',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF1A6B4A)),
      ),
      routerConfig: router,
    );
  }
}

// ── Shell scaffold with nav rail ──────────────────────────────────────────────
class _AdminShell extends ConsumerWidget {
  const _AdminShell({required this.child});
  final Widget child;

  static const _destinations = [
    (path: '/dashboard',     icon: Icons.dashboard_outlined,       label: 'Dashboard'),
    (path: '/users',         icon: Icons.people_outlined,         label: 'Utilisateurs'),
    (path: '/applications',  icon: Icons.school_outlined,         label: 'Tuteurs'),
    (path: '/link-requests', icon: Icons.family_restroom_outlined, label: 'Liaisons'),
    (path: '/sessions',      icon: Icons.video_call_outlined,     label: 'Sessions'),
    (path: '/payments',      icon: Icons.payment_outlined,        label: 'Paiements'),
    (path: '/content',       icon: Icons.book_outlined,           label: 'Contenu'),
  ];

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final location = GoRouterState.of(context).matchedLocation;
    final idx      = _destinations.indexWhere((d) => d.path == location).clamp(0, _destinations.length - 1);
    final extended = MediaQuery.of(context).size.width > 800;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Suklu Admin'),
        backgroundColor: const Color(0xFF1A6B4A),
        foregroundColor: Colors.white,
        actions: [
          IconButton(
            tooltip: 'Déconnexion',
            icon: const Icon(Icons.logout),
            onPressed: () => FirebaseAuth.instance.signOut(),
          ),
        ],
      ),
      body: Row(
        children: [
          NavigationRail(
            extended: extended,
            selectedIndex: idx,
            onDestinationSelected: (i) => context.go(_destinations[i].path),
            destinations: _destinations.map((d) => NavigationRailDestination(
              icon:  Icon(d.icon),
              label: Text(d.label),
            )).toList(),
          ),
          const VerticalDivider(thickness: 1, width: 1),
          Expanded(child: child),
        ],
      ),
    );
  }
}

